version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(ci)'
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(deps-dev)'
    groups:
      production:
        dependency-type: production
        update-types: [minor, patch]
      development:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: docker
    directories:
      - /apps/api
      - /apps/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(docker)'
