export { registerAccountsModule } from './composition/register.js'
export type { AccountsConfig, AccountsModuleDeps } from './composition/container.js'
export { createAccountsFacade } from './composition/facade.js'
export type { AccountsFacade } from './composition/facade.js'
export { AccountCreated } from './domain/events/account-created/index.js'
export { AccountCreationRejected } from './domain/events/account-creation-rejected/index.js'
export { AccountDeletionRequested } from './domain/events/account-deletion-requested/index.js'
export { BetaCapacityReached } from './domain/events/beta-capacity-reached/index.js'
export { ConsentAccepted } from './domain/events/consent-accepted/index.js'
export { GoogleLoginRejected } from './domain/events/google-login-rejected/index.js'
export { LoginRejected } from './domain/events/login-rejected/index.js'
