export type IconName =
  | 'audio-wave-01'
  | 'cancel-01'
  | 'chart-increase'
  | 'checkmark-circle-02'
  | 'circle'
  | 'clock-01'
  | 'logout-01'
  | 'menu-01'
  | 'mic-01'
  | 'pencil-edit-02'
  | 'sidebar-left'
  | 'stop'
  | 'view'
  | 'view-off'
